// import './styles/globals.css'; 
// import Navbar from '../components/Navbar';
// import Footer from '../components/Footer';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <Navbar />
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }


import './styles/globals.css'; // Essential for Tailwind and custom global styles
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export const metadata = {
  title: "Ivy M Coaching",
  description: "Empowering your journey with Ivy M Coaching.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen h-full bg-gray-100 text-gray-900">
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
